apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: kcl-bucket
  labels:
    language: kcl
spec:
  compositeTypeRef:
    apiVersion: krossplane.cloud/v1alpha1
    kind: StorageBucket
  mode: Pipeline
  pipeline:
  - step: normal
    functionRef:
      name: crossplane-contrib-function-kcl
    input:
      apiVersion: krm.kcl.dev/v1alpha1
      kind: KCLInput
      spec:
        source: |
          oxr = option("params").oxr
          _items = [
              {
                  apiVersion = "s3.services.k8s.aws/v1alpha1"
                  kind = "Bucket"
                  metadata = {
                      name = oxr.spec.id
                      annotations = {
                          "krm.kcl.dev/ready" = True # we need a custom function to check for ready ACK.ResourceSynced = Ready ?!
                          "services.k8s.aws/region": oxr.spec.parameters.region
                          "krm.kcl.dev/composition-resource-name" = "bucket"
                      }
                  }
                  spec = {
                      name = oxr.metadata.name
                  }
              }
          ]

          items = _items
