apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crossplane:ack-resources:aggregate-to-crossplane
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups:
  - s3.services.k8s.aws
  resources:
  - buckets
  - buckets/status
  - buckets/finalizers
  verbs:
  - '*'
